name: flutter_project_mobile
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1


environment:
  sdk: '>=3.0.5 <4.0.0'


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_native_splash: ^2.3.1
  get: ^4.6.5
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/logo-hamburger.png
  image_dark: assets/images/logo-hamburger.png

android_12:
  image: assets/images/logo-hamburger.png
  icon_background_color: "#f7f6f1"
  image_dark: assets/images/logo-hamburger.png
  icon_background_color_dark: "#272727" 
  
  
  flutter_lints: ^2.0.0

  

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
