name: flutter_project_mobile_v2
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  
  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  # modern_form_line_awesome_icons: ^2.0.1
  
  flutter_native_splash: ^2.3.2
  
  ## -- STATE MANAGEMENT
  get: ^4.6.6

  ## -- ONBOARDING PACKAGES
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

  ## -- OTP TEXT FIELD PACKAGE
  flutter_otp_text_field: ^1.1.1

  ## -- FIREBASE PACKAGES
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.6
  flutter_facebook_auth: ^6.1.1
  google_sign_in: ^6.2.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^3.0.1


flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/burger.png
  image_dark: assets/images/burger.png

  android_12:
    image: assets/images/burger.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/burger.png
    icon_background_color_dark: "#272727"


flutter:
  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/logo/
    - assets/images/forget_password/
    - assets/images/dashboard/
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
